### ISSUE TITLE
Perimeter of Squre 

### ISSUE THREAD

**Issue by Mahmoud-M-Abdelhafez** [Mahmoud-M-Abdelhafez/Coding-Tracker#2]
Rewrite Code of Class Squre in Calc Perimeter Method ---- squre = length * 4 or (length * width ) * 2 

@Kareem-Mohamed0

**Comment by Kareem-Mohamed0** [comment]
ok ya khaaawal

**Comment by Kareem-Mohamed0** [comment]
(length + width)*2
not *
